// Пиксельные значки форматов на карточках Ириски, 12×12.
// L — контур (--px-line), A — пятно окраса своей карточки (--icon-fill,
// задаёт iriska.ts). Значки статичные: движение на экране — только отскок.

import type { FormatIcon } from './content';
import { renderPixelImage } from './pixelcats';

const ICONS: Record<FormatIcon, string[]> = {
  dinner: [
    '..L.L.L..LL.',
    '..L.L.L..LAL',
    '..L.L.L..LAL',
    '..LLLLL..LAL',
    '..LAAAL..LAL',
    '...LAL...LAL',
    '...LAL...LLL',
    '...LAL....L.',
    '...LAL...LAL',
    '...LAL...LAL',
    '...LAL...LAL',
    '...LLL...LLL',
  ],
  movie: [
    '...LL..LL...',
    '..LAAL.LAAL.',
    '.LAAAALAAAAL',
    '.LLLLLLLLLLL',
    '.LAALAALAAL.',
    '.LAALAALAAL.',
    '..LALAALAL..',
    '..LALAALAL..',
    '..LALAALAL..',
    '..LALAALAL..',
    '...LLLLLL...',
    '............',
  ],
  park: [
    '.....LL.....',
    '....LAAL....',
    '.LL.LAAL.LL.',
    '.LAL.LL.LAL.',
    'LAAALAALAAAL',
    '.LAAAAAAAAL.',
    '..LAAAAAAL..',
    'LLLAAAAAALLL',
    '.LAAAAAAAAL.',
    '..LLLLLLLL..',
    '.....LL.....',
    '.....LL.....',
  ],
  pottery: [
    '...LLLLLL...',
    '....LAAL....',
    '....LAAL....',
    '...LAAAAL...',
    '..LAAAAAAL..',
    '.LAAAAAAAAL.',
    '.LAALLLLAAL.',
    '.LAAAAAAAAL.',
    '..LAAAAAAL..',
    '...LAAAAL...',
    '...LLLLLL...',
    '............',
  ],
  cabin: [
    '........LL..',
    '.....LL.LL..',
    '....LAAL.L..',
    '...LAAAAL...',
    '..LAAAAAAL..',
    '.LAAAAAAAAL.',
    'LLLLLLLLLLLL',
    '.L........L.',
    '.L.LLL.LL.L.',
    '.L.LAL.LL.L.',
    '.L.LAL....L.',
    '.LLLLLLLLLL.',
  ],
  planetarium: [
    '.....LL.....',
    '.....LL.....',
    '....LAAL....',
    'LLLLLAALLLLL',
    '.LAAAAAAAAL.',
    '..LAAAAAAL..',
    '...LAAAAL...',
    '..LAAAAAAL..',
    '..LAALLAAL..',
    '.LAL....LAL.',
    '.LL......LL.',
    '............',
  ],
  custom: [
    '.........LL.',
    '........LAAL',
    '.......LAAL.',
    '......LAAL..',
    '.....LAAL...',
    '....LAAL....',
    '...LAAL.....',
    '..LAAL......',
    '..LLL.......',
    '.LL.........',
    'L...........',
    '............',
  ],
};

export function renderFormatIcon(icon: FormatIcon): SVGSVGElement {
  return renderPixelImage(ICONS[icon], 'format-icon');
}
